# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['category_auto_increment_id'],
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'date published')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('product_auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to=b'product_images')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('category_auto_increment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbs_application.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(blank=True, default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, default=b'')),
                ('phone', models.CharField(blank=True, default=b'', max_length=20)),
                ('city', models.CharField(blank=True, default=b'', max_length=100)),
                ('country', models.CharField(blank=True, default=b'', max_length=100)),
                ('balance', models.CharField(blank=True, default=b'', max_length=50)),
                ('num_of_transactions', models.PositiveIntegerField(blank=True, default=b'')),
                ('num_of_suspensions', models.CharField(blank=True, default=b'', max_length=50)),
                ('status', models.TextField(blank=True, default=b'')),
                ('credit_card', models.PositiveIntegerField(blank=True, default=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user_auto_increment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbs_application.UserProfile'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user_auto_increment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbs_application.UserProfile'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbs_application.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbs_application.UserProfile'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbs_application.UserProfile'),
        ),
    ]
