# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbs_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
    ]
