# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbs_application', '0002_auto_20161201_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile'},
        ),
    ]
