# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbs_application', '0004_auto_20161201_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
