# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbs_application', '0005_auto_20161201_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
